#!/bin/bash
# Auto-generated by DojoSeedExporter — source of truth is Unity QuestionBank
# Profile: dev | Questions: 54

cd ~/flag_trivia

# Algeria (id=1)
sozo execute flag_trivia-actions seed_question --calldata 1,0,100 --profile dev
# Angola (id=2)
sozo execute flag_trivia-actions seed_question --calldata 2,0,100 --profile dev
# Benin (id=3)
sozo execute flag_trivia-actions seed_question --calldata 3,0,100 --profile dev
# Botswana (id=4)
sozo execute flag_trivia-actions seed_question --calldata 4,0,100 --profile dev
# Burkina Faso (id=5)
sozo execute flag_trivia-actions seed_question --calldata 5,0,100 --profile dev
# Burundi (id=6)
sozo execute flag_trivia-actions seed_question --calldata 6,0,100 --profile dev
# Cape Verde (id=7)
sozo execute flag_trivia-actions seed_question --calldata 7,0,100 --profile dev
# Cameroon (id=8)
sozo execute flag_trivia-actions seed_question --calldata 8,0,100 --profile dev
# Central African Republic (id=9)
sozo execute flag_trivia-actions seed_question --calldata 9,0,100 --profile dev
# Chad (id=10)
sozo execute flag_trivia-actions seed_question --calldata 10,0,100 --profile dev
# The Comoros (id=11)
sozo execute flag_trivia-actions seed_question --calldata 11,0,100 --profile dev
# Democratic Republic of the Congo (id=12)
sozo execute flag_trivia-actions seed_question --calldata 12,0,100 --profile dev
# Republic of the Congo (id=13)
sozo execute flag_trivia-actions seed_question --calldata 13,0,100 --profile dev
# Cote d'Ivoire (id=14)
sozo execute flag_trivia-actions seed_question --calldata 14,0,100 --profile dev
# Djibouti (id=15)
sozo execute flag_trivia-actions seed_question --calldata 15,0,100 --profile dev
# Egypt (id=16)
sozo execute flag_trivia-actions seed_question --calldata 16,0,100 --profile dev
# Equatorial Guinea (id=17)
sozo execute flag_trivia-actions seed_question --calldata 17,0,100 --profile dev
# Eritrea (id=18)
sozo execute flag_trivia-actions seed_question --calldata 18,0,100 --profile dev
# Eswatini (id=19)
sozo execute flag_trivia-actions seed_question --calldata 19,0,100 --profile dev
# Ethiopia (id=20)
sozo execute flag_trivia-actions seed_question --calldata 20,0,100 --profile dev
# Gabon (id=21)
sozo execute flag_trivia-actions seed_question --calldata 21,0,100 --profile dev
# The Gambia (id=22)
sozo execute flag_trivia-actions seed_question --calldata 22,0,100 --profile dev
# Ghana (id=23)
sozo execute flag_trivia-actions seed_question --calldata 23,0,100 --profile dev
# Guinea (id=24)
sozo execute flag_trivia-actions seed_question --calldata 24,0,100 --profile dev
# Guinea Bissau (id=25)
sozo execute flag_trivia-actions seed_question --calldata 25,0,100 --profile dev
# Kenya (id=26)
sozo execute flag_trivia-actions seed_question --calldata 26,0,100 --profile dev
# Lesotho (id=27)
sozo execute flag_trivia-actions seed_question --calldata 27,0,100 --profile dev
# Liberia (id=28)
sozo execute flag_trivia-actions seed_question --calldata 28,0,100 --profile dev
# Libya (id=29)
sozo execute flag_trivia-actions seed_question --calldata 29,0,100 --profile dev
# Chad (id=10)
sozo execute flag_trivia-actions seed_question --calldata 10,0,100 --profile dev
# Malawi (id=31)
sozo execute flag_trivia-actions seed_question --calldata 31,0,100 --profile dev
# Mali (id=32)
sozo execute flag_trivia-actions seed_question --calldata 32,0,100 --profile dev
# Mauritania (id=33)
sozo execute flag_trivia-actions seed_question --calldata 33,0,100 --profile dev
# Mauritius (id=34)
sozo execute flag_trivia-actions seed_question --calldata 34,0,100 --profile dev
# Morroco (id=35)
sozo execute flag_trivia-actions seed_question --calldata 35,0,100 --profile dev
# Mozambique (id=36)
sozo execute flag_trivia-actions seed_question --calldata 36,0,100 --profile dev
# Namibia (id=37)
sozo execute flag_trivia-actions seed_question --calldata 37,0,100 --profile dev
# Niger (id=38)
sozo execute flag_trivia-actions seed_question --calldata 38,0,100 --profile dev
# Nigeria (id=39)
sozo execute flag_trivia-actions seed_question --calldata 39,0,100 --profile dev
# Rwanda (id=40)
sozo execute flag_trivia-actions seed_question --calldata 40,0,100 --profile dev
# Sao Tome and Principe (id=41)
sozo execute flag_trivia-actions seed_question --calldata 41,0,100 --profile dev
# Senegal (id=42)
sozo execute flag_trivia-actions seed_question --calldata 42,0,100 --profile dev
# Seychelles (id=43)
sozo execute flag_trivia-actions seed_question --calldata 43,0,100 --profile dev
# Sierra Leone (id=44)
sozo execute flag_trivia-actions seed_question --calldata 44,0,100 --profile dev
# Somalia (id=45)
sozo execute flag_trivia-actions seed_question --calldata 45,0,100 --profile dev
# South Africa (id=46)
sozo execute flag_trivia-actions seed_question --calldata 46,0,100 --profile dev
# South Sudan (id=47)
sozo execute flag_trivia-actions seed_question --calldata 47,0,100 --profile dev
# Sudan (id=48)
sozo execute flag_trivia-actions seed_question --calldata 48,0,100 --profile dev
# Tanzania (id=49)
sozo execute flag_trivia-actions seed_question --calldata 49,0,100 --profile dev
# Togo (id=50)
sozo execute flag_trivia-actions seed_question --calldata 50,0,100 --profile dev
# Tunisia (id=51)
sozo execute flag_trivia-actions seed_question --calldata 51,0,100 --profile dev
# Uganda (id=52)
sozo execute flag_trivia-actions seed_question --calldata 52,0,100 --profile dev
# Zambia (id=53)
sozo execute flag_trivia-actions seed_question --calldata 53,0,100 --profile dev
# Zimbabwe (id=54)
sozo execute flag_trivia-actions seed_question --calldata 54,0,100 --profile dev
