// Generated by dojo-bindgen on Fri, 6 Mar 2026 21:22:07 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `flag_trivia::models::LeaderboardEntry` model
public class flag_trivia_LeaderboardEntry : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("session_id")]
        public uint session_id;

        [ModelField("score")]
        public uint score;

        [ModelField("correct_count")]
        public byte correct_count;

        [ModelField("total_questions")]
        public byte total_questions;

        [ModelField("completed_at")]
        public ulong completed_at;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        