// Generated by dojo-bindgen on Fri, 6 Mar 2026 21:22:07 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `flag_trivia::models::Question` model
public class flag_trivia_Question : ModelInstance {
    [ModelField("question_id")]
        public uint question_id;

        [ModelField("answer_hash")]
        public FieldElement answer_hash;

        [ModelField("base_points")]
        public uint base_points;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        