using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;

public class DojoSeedExporter : EditorWindow
{
    private QuestionBank questionBank;
    private string profile = "dev";
    private uint basePoints = 100;

    [MenuItem("Dojo/Seed Question Exporter")]
    public static void ShowWindow()
    {
        GetWindow<DojoSeedExporter>("Dojo Seed Exporter");
    }

    void OnGUI()
    {
        GUILayout.Label("Dojo Seed Question Exporter", EditorStyles.boldLabel);
        EditorGUILayout.Space();

        questionBank = (QuestionBank)EditorGUILayout.ObjectField("Question Bank", questionBank, typeof(QuestionBank), false);
        profile = EditorGUILayout.TextField("Profile", profile);
        basePoints = (uint)EditorGUILayout.IntField("Base Points", (int)basePoints);

        EditorGUILayout.Space();

        if (questionBank == null)
        {
            EditorGUILayout.HelpBox("Assign a Question Bank to continue.", MessageType.Info);
            return;
        }

        EditorGUILayout.LabelField($"Questions found: {questionBank.questions.Length}");
        EditorGUILayout.HelpBox("Correct answer is always seeded as index 0. Unity sends 0 for correct, 1 for wrong.", MessageType.Info);

        int missing = 0;
        foreach (var q in questionBank.questions)
            if (q.questionId <= 0) missing++;
        if (missing > 0)
            EditorGUILayout.HelpBox($"{missing} question(s) have questionId <= 0. Set a unique ID for each.", MessageType.Warning);

        EditorGUILayout.Space();

        if (GUILayout.Button("Export Seed Script"))
            ExportScript();

        if (GUILayout.Button("Print to Console"))
            PrintToConsole();
    }

    string BuildScript()
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/bin/bash");
        sb.AppendLine("# Auto-generated by DojoSeedExporter — source of truth is Unity QuestionBank");
        sb.AppendLine($"# Profile: {profile} | Questions: {questionBank.questions.Length}");
        sb.AppendLine();
        sb.AppendLine("cd ~/flag_trivia");
        sb.AppendLine();

        foreach (var q in questionBank.questions)
        {
            sb.AppendLine($"# {q.countryName} (id={q.questionId})");
            sb.AppendLine($"sozo execute flag_trivia-actions seed_question --calldata {q.questionId},0,{basePoints} --profile {profile}");
        }

        return sb.ToString();
    }

    void ExportScript()
    {
        string path = EditorUtility.SaveFilePanel("Save seed script", "", "seed_questions.sh", "sh");
        if (string.IsNullOrEmpty(path)) return;

        File.WriteAllText(path, BuildScript());
        Debug.Log($"Seed script exported to: {path}");
    }

    void PrintToConsole()
    {
        Debug.Log(BuildScript());
    }
}
